#!/usr/bin/env ruby

#site 'https://supermarket.getchef.com/api/v1'
site 'http://community.opscode.com/api/v1'

cookbook 'openvpn', '~> 2.1.0'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
